name: CI

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]

jobs:
 sync-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: build images.yaml # bash build_images.sh
        run: |
          cd $GITHUB_WORKSPACE
          chmod +x build_images.sh
          ./build_images.sh
          cat auth.yaml
          cat images.yaml
        shell: bash
      - uses: hhyasdf/image-sync-action@v1.1
        with:
          auth_file: ./auth.yaml
          images_file: ./images.yaml
          version: latest
          proc: 20
        env:
          ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
          ACR_USER: "${{ secrets.ACR_USER }}"
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: "${{ secrets.DOCKER_USERNAME }}"
